Do not try to put in history if name of calc is too long
Prevents critical failure of the script like that:
    fs.js:101
          throw err;  // Forgot a callback but don't know where? Use
    NODE_DEBUG=fs
          ^

    Error: ENAMETOOLONG: name too long, mkdir '../static/history/…